//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Attendance.Resources.Localization.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Page {
            get {
                return ResourceManager.GetString("About_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string Attendance_Page {
            get {
                return ResourceManager.GetString("Attendance_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string Attendance_title {
            get {
                return ResourceManager.GetString("Attendance_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Date.
        /// </summary>
        internal static string AttendanceDate {
            get {
                return ResourceManager.GetString("AttendanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string btn_enter_tittle {
            get {
                return ResourceManager.GetString("btn_enter_tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string btn_share_tittle {
            get {
                return ResourceManager.GetString("btn_share_tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business URL.
        /// </summary>
        internal static string BusinessURL_Page {
            get {
                return ResourceManager.GetString("BusinessURL_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Common_LastName {
            get {
                return ResourceManager.GetString("Common_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Image.
        /// </summary>
        internal static string CommonClean {
            get {
                return ResourceManager.GetString("CommonClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CommonEmail {
            get {
                return ResourceManager.GetString("CommonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string CommonEnter {
            get {
                return ResourceManager.GetString("CommonEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CommonName {
            get {
                return ResourceManager.GetString("CommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CommonNo {
            get {
                return ResourceManager.GetString("CommonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string CommonPN {
            get {
                return ResourceManager.GetString("CommonPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string CommonPrint {
            get {
                return ResourceManager.GetString("CommonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string CommonSave {
            get {
                return ResourceManager.GetString("CommonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        internal static string CommonStudentName {
            get {
                return ResourceManager.GetString("CommonStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string CommonYes {
            get {
                return ResourceManager.GetString("CommonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string CourseGrade {
            get {
                return ResourceManager.GetString("CourseGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string CourseGroup {
            get {
                return ResourceManager.GetString("CourseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course List.
        /// </summary>
        internal static string CourseRegisterCourseList {
            get {
                return ResourceManager.GetString("CourseRegisterCourseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Subjects.
        /// </summary>
        internal static string CourseRegisterSeeSubjects {
            get {
                return ResourceManager.GetString("CourseRegisterSeeSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string CourseRegisterTitle {
            get {
                return ResourceManager.GetString("CourseRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string Home_Page {
            get {
                return ResourceManager.GetString("Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Page {
            get {
                return ResourceManager.GetString("Login_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have account?.
        /// </summary>
        internal static string LoginCreateAccount {
            get {
                return ResourceManager.GetString("LoginCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string LoginForgotPass {
            get {
                return ResourceManager.GetString("LoginForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing In.
        /// </summary>
        internal static string LoginSingIn {
            get {
                return ResourceManager.GetString("LoginSingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string LoginSingup {
            get {
                return ResourceManager.GetString("LoginSingup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Avialable.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QR Code.
        /// </summary>
        internal static string QR_Code_Generated {
            get {
                return ResourceManager.GetString("QR_Code_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Register.
        /// </summary>
        internal static string Register_Page {
            get {
                return ResourceManager.GetString("Register_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string SchoolGroup_grade {
            get {
                return ResourceManager.GetString("SchoolGroup_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string SchoolGroup_group {
            get {
                return ResourceManager.GetString("SchoolGroup_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SchoolGroup_name {
            get {
                return ResourceManager.GetString("SchoolGroup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Grade.
        /// </summary>
        internal static string SchoolGroup_Page {
            get {
                return ResourceManager.GetString("SchoolGroup_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select School Grade.
        /// </summary>
        internal static string SchoolGroupTitle {
            get {
                return ResourceManager.GetString("SchoolGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Page {
            get {
                return ResourceManager.GetString("Settings_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Delete.
        /// </summary>
        internal static string SingleDelete {
            get {
                return ResourceManager.GetString("SingleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student_Title {
            get {
                return ResourceManager.GetString("Student_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Registration.
        /// </summary>
        internal static string StudentRegister {
            get {
                return ResourceManager.GetString("StudentRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Students.
        /// </summary>
        internal static string StudentsSeeStudent {
            get {
                return ResourceManager.GetString("StudentsSeeStudent", resourceCulture);
            }
        }
    }
}
