//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Attendance.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Attendance.Resources.Localization.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Page {
            get {
                return ResourceManager.GetString("About_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        internal static string Attendace_CameraF {
            get {
                return ResourceManager.GetString("Attendace_CameraF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rear.
        /// </summary>
        internal static string Attendace_CameraT {
            get {
                return ResourceManager.GetString("Attendace_CameraT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash.
        /// </summary>
        internal static string Attendace_Light {
            get {
                return ResourceManager.GetString("Attendace_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Registered {0}..
        /// </summary>
        internal static string Attendace_StudentRegistered {
            get {
                return ResourceManager.GetString("Attendace_StudentRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student {0} has already been registered..
        /// </summary>
        internal static string Attendance_AlreadyRegistered {
            get {
                return ResourceManager.GetString("Attendance_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance saved {0}..
        /// </summary>
        internal static string Attendance_DataSaved {
            get {
                return ResourceManager.GetString("Attendance_DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This student {0} is not registred in this class..
        /// </summary>
        internal static string Attendance_NotRegistered {
            get {
                return ResourceManager.GetString("Attendance_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string Attendance_Page {
            get {
                return ResourceManager.GetString("Attendance_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data saved by {0}..
        /// </summary>
        internal static string Attendance_Save {
            get {
                return ResourceManager.GetString("Attendance_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan Barcode....
        /// </summary>
        internal static string Attendance_Scanning {
            get {
                return ResourceManager.GetString("Attendance_Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        internal static string Attendance_title {
            get {
                return ResourceManager.GetString("Attendance_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Date.
        /// </summary>
        internal static string AttendanceDate {
            get {
                return ResourceManager.GetString("AttendanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup DB.
        /// </summary>
        internal static string Backup_DB {
            get {
                return ResourceManager.GetString("Backup_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string btn_enter_tittle {
            get {
                return ResourceManager.GetString("btn_enter_tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string btn_share_tittle {
            get {
                return ResourceManager.GetString("btn_share_tittle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business URL.
        /// </summary>
        internal static string BusinessURL_Page {
            get {
                return ResourceManager.GetString("BusinessURL_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to exit?.
        /// </summary>
        internal static string CloseAppMsg {
            get {
                return ResourceManager.GetString("CloseAppMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information not found..
        /// </summary>
        internal static string Common_InfoNotFound {
            get {
                return ResourceManager.GetString("Common_InfoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error {0}..
        /// </summary>
        internal static string Common_InternalError {
            get {
                return ResourceManager.GetString("Common_InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Common_LastName {
            get {
                return ResourceManager.GetString("Common_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Still in process..
        /// </summary>
        internal static string Common_Processing {
            get {
                return ResourceManager.GetString("Common_Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string Common_Question {
            get {
                return ResourceManager.GetString("Common_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Successful..
        /// </summary>
        internal static string Common_RecordSaved {
            get {
                return ResourceManager.GetString("Common_RecordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Failed..
        /// </summary>
        internal static string Common_SaveFailed {
            get {
                return ResourceManager.GetString("Common_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        internal static string Common_Successful {
            get {
                return ResourceManager.GetString("Common_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean Image.
        /// </summary>
        internal static string CommonClean {
            get {
                return ResourceManager.GetString("CommonClean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CommonEmail {
            get {
                return ResourceManager.GetString("CommonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string CommonEnter {
            get {
                return ResourceManager.GetString("CommonEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CommonName {
            get {
                return ResourceManager.GetString("CommonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string CommonNo {
            get {
                return ResourceManager.GetString("CommonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string CommonPN {
            get {
                return ResourceManager.GetString("CommonPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string CommonPrint {
            get {
                return ResourceManager.GetString("CommonPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string CommonSave {
            get {
                return ResourceManager.GetString("CommonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        internal static string CommonStudentName {
            get {
                return ResourceManager.GetString("CommonStudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string CommonWarning {
            get {
                return ResourceManager.GetString("CommonWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string CommonYes {
            get {
                return ResourceManager.GetString("CommonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string CourseGrade {
            get {
                return ResourceManager.GetString("CourseGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string CourseGroup {
            get {
                return ResourceManager.GetString("CourseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course List.
        /// </summary>
        internal static string CourseRegisterCourseList {
            get {
                return ResourceManager.GetString("CourseRegisterCourseList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Subjects.
        /// </summary>
        internal static string CourseRegisterSeeSubjects {
            get {
                return ResourceManager.GetString("CourseRegisterSeeSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string CourseRegisterTitle {
            get {
                return ResourceManager.GetString("CourseRegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        internal static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string Home_Page {
            get {
                return ResourceManager.GetString("Home_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to log in with fingerprint/faceID?.
        /// </summary>
        internal static string Login_FingerPrint {
            get {
                return ResourceManager.GetString("Login_FingerPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please authenticate FingerPrint..
        /// </summary>
        internal static string Login_FingerPrintAuth {
            get {
                return ResourceManager.GetString("Login_FingerPrintAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fingerprint does not match the stored one..
        /// </summary>
        internal static string Login_FingerPrintError {
            get {
                return ResourceManager.GetString("Login_FingerPrintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with credentials..
        /// </summary>
        internal static string Login_LoginCredentials {
            get {
                return ResourceManager.GetString("Login_LoginCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Page {
            get {
                return ResourceManager.GetString("Login_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add the required information..
        /// </summary>
        internal static string Login_RequiredFields {
            get {
                return ResourceManager.GetString("Login_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        internal static string Login_WrongPass {
            get {
                return ResourceManager.GetString("Login_WrongPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have account?.
        /// </summary>
        internal static string LoginCreateAccount {
            get {
                return ResourceManager.GetString("LoginCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginEmail {
            get {
                return ResourceManager.GetString("LoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        internal static string LoginForgotPass {
            get {
                return ResourceManager.GetString("LoginForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing In.
        /// </summary>
        internal static string LoginSingIn {
            get {
                return ResourceManager.GetString("LoginSingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string LoginSingup {
            get {
                return ResourceManager.GetString("LoginSingup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string Month_Apr {
            get {
                return ResourceManager.GetString("Month_Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        internal static string Month_Aug {
            get {
                return ResourceManager.GetString("Month_Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string Month_Dec {
            get {
                return ResourceManager.GetString("Month_Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        internal static string Month_Feb {
            get {
                return ResourceManager.GetString("Month_Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        internal static string Month_Jan {
            get {
                return ResourceManager.GetString("Month_Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        internal static string Month_Jul {
            get {
                return ResourceManager.GetString("Month_Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        internal static string Month_Jun {
            get {
                return ResourceManager.GetString("Month_Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        internal static string Month_Mar {
            get {
                return ResourceManager.GetString("Month_Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        internal static string Month_May {
            get {
                return ResourceManager.GetString("Month_May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string Month_Nov {
            get {
                return ResourceManager.GetString("Month_Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        internal static string Month_Oct {
            get {
                return ResourceManager.GetString("Month_Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string Month_Sep {
            get {
                return ResourceManager.GetString("Month_Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month_Title {
            get {
                return ResourceManager.GetString("Month_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Avialable.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        internal static string PrintDoc_Course {
            get {
                return ResourceManager.GetString("PrintDoc_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document file is opened..
        /// </summary>
        internal static string PrintDoc_DocOpen {
            get {
                return ResourceManager.GetString("PrintDoc_DocOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Name.
        /// </summary>
        internal static string PrintDoc_Name {
            get {
                return ResourceManager.GetString("PrintDoc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was generated correctly, Do you want to share it?.
        /// </summary>
        internal static string PrintDoc_Saved {
            get {
                return ResourceManager.GetString("PrintDoc_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share File..
        /// </summary>
        internal static string PrintDoc_ShareFile {
            get {
                return ResourceManager.GetString("PrintDoc_ShareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance List.
        /// </summary>
        internal static string PrintDoc_Title {
            get {
                return ResourceManager.GetString("PrintDoc_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create QR Code.
        /// </summary>
        internal static string QR_Code_Generated {
            get {
                return ResourceManager.GetString("QR_Code_Generated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Register.
        /// </summary>
        internal static string Register_Page {
            get {
                return ResourceManager.GetString("Register_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you already have an account?.
        /// </summary>
        internal static string Registrer_LogIn {
            get {
                return ResourceManager.GetString("Registrer_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to see the student list?.
        /// </summary>
        internal static string SchooGradel_ListView {
            get {
                return ResourceManager.GetString("SchooGradel_ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a course..
        /// </summary>
        internal static string SchoolGrade_CourseNotSelected {
            get {
                return ResourceManager.GetString("SchoolGrade_CourseNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A record already exists..
        /// </summary>
        internal static string SchoolGrade_RecordExist {
            get {
                return ResourceManager.GetString("SchoolGrade_RecordExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string SchoolGroup_grade {
            get {
                return ResourceManager.GetString("SchoolGroup_grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string SchoolGroup_group {
            get {
                return ResourceManager.GetString("SchoolGroup_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string SchoolGroup_name {
            get {
                return ResourceManager.GetString("SchoolGroup_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Grade.
        /// </summary>
        internal static string SchoolGroup_Page {
            get {
                return ResourceManager.GetString("SchoolGroup_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select School Grade.
        /// </summary>
        internal static string SchoolGroupTitle {
            get {
                return ResourceManager.GetString("SchoolGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Page {
            get {
                return ResourceManager.GetString("Settings_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Delete.
        /// </summary>
        internal static string SingleDelete {
            get {
                return ResourceManager.GetString("SingleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student is assigned correctly. Do you want to add another student?.
        /// </summary>
        internal static string Student_Added {
            get {
                return ResourceManager.GetString("Student_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student is already registered in this course..
        /// </summary>
        internal static string Student_Exists {
            get {
                return ResourceManager.GetString("Student_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student_Title {
            get {
                return ResourceManager.GetString("Student_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Registration.
        /// </summary>
        internal static string StudentRegister {
            get {
                return ResourceManager.GetString("StudentRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Students.
        /// </summary>
        internal static string StudentsSeeStudent {
            get {
                return ResourceManager.GetString("StudentsSeeStudent", resourceCulture);
            }
        }
    }
}
